import { createPlaylist } from "./playlist.js";

const TRACKS=["Felt Keys for Marchers.mp3","Faith build up.mp3","Gentle+Dreams (1).mp3","Gentle+Dreams.mp3"];
const THEMES=["light","dark","ocean","sunset"];

const css=`.ambient-controls{position:fixed;right:10px;top:10px;z-index:999;display:flex;gap:6px}.ambient-btn{width:34px;height:34px;border:1px solid var(--line-strong,#ddd);border-radius:50%;background:var(--btn-bg,#fff);color:var(--btn-fg,#333);display:flex;align-items:center;justify-content:center;font-size:15px;cursor:pointer;box-shadow:0 2px 8px rgba(0,0,0,.15)}.ambient-btn.off{opacity:.42;filter:grayscale(1)}html[data-theme="dark"]{--bg:#0f0f0f!important;--app:#0f0f0f!important;--panel:#0f0f0f!important;--panel-alt:#1c1c1c!important;--text:#f1f1f1!important;--text-mid:#c9c9c9!important;--text-dim:#a3a3a3!important;--line:#2c2c2c!important;--line-soft:#262626!important;--line-row:#242424!important;--line-strong:#333!important;--btn-bg:#202020!important;--btn-fg:#f1f1f1!important}html[data-theme="ocean"]{--bg:linear-gradient(165deg,#08172e,#0e2f52 55%,#123f63)!important;--app:transparent!important;--panel:rgba(4,16,34,.42)!important;--panel-alt:rgba(4,16,34,.6)!important;--text:#eaf3ff!important;--text-mid:#c8dcf2!important;--text-dim:#a8c6e2!important;--line:rgba(255,255,255,.15)!important;--line-soft:rgba(255,255,255,.1)!important;--line-row:rgba(255,255,255,.09)!important;--line-strong:rgba(255,255,255,.2)!important;--btn-bg:rgba(255,255,255,.16)!important;--btn-fg:#eaf3ff!important}html[data-theme="sunset"]{--bg:linear-gradient(165deg,#210b28,#5c2338 52%,#8d3f2b)!important;--app:transparent!important;--panel:rgba(24,6,14,.46)!important;--panel-alt:rgba(24,6,14,.62)!important;--text:#fff4ec!important;--text-mid:#f4d6c8!important;--text-dim:#e6bdac!important;--line:rgba(255,255,255,.16)!important;--line-soft:rgba(255,255,255,.11)!important;--line-row:rgba(255,255,255,.1)!important;--line-strong:rgba(255,255,255,.21)!important;--btn-bg:rgba(255,255,255,.17)!important;--btn-fg:#fff4ec!important}`;

function addStyle(){const s=document.createElement("style");s.textContent=css;document.head.appendChild(s)}
function setupTheme(btn){let i=0;try{i=Math.max(0,THEMES.indexOf(localStorage.getItem("souls-theme")))}catch(e){}function apply(){const t=THEMES[i];if(t==="light")document.documentElement.removeAttribute("data-theme");else document.documentElement.dataset.theme=t;try{localStorage.setItem("souls-theme",t)}catch(e){}}btn.onclick=()=>{i=(i+1)%THEMES.length;apply()};apply()}
function setupMusic(btn){const audio=document.createElement("audio");audio.preload="auto";audio.muted=true;audio.volume=.18;document.body.appendChild(audio);const playlist=createPlaylist({tracks:TRACKS});let current=null,exhausted=false;function cue(){const n=playlist.next();if(!n){exhausted=true;return false}current=n;audio.src=n;return true}function render(){btn.classList.toggle("off",audio.paused||exhausted)}async function play(){if(exhausted)return;if(!current&&!cue())return;audio.muted=false;try{await audio.play()}catch(e){}render()}function pause(){audio.pause();render()}audio.onended=()=>{current=null;if(cue())play()};audio.onerror=()=>{if(current)playlist.retire(current);current=null;if(cue())play()};btn.onclick=e=>{e.stopPropagation();if(audio.paused){play();try{localStorage.setItem("souls-music","on")}catch(e){}}else{pause();try{localStorage.setItem("souls-music","off")}catch(e){}}};let wanted=true;try{wanted=localStorage.getItem("souls-music")!=="off"}catch(e){}const gesture=()=>{if(wanted)play();document.removeEventListener("click",gesture);document.removeEventListener("touchstart",gesture);document.removeEventListener("keydown",gesture)};document.addEventListener("click",gesture,{once:true});document.addEventListener("touchstart",gesture,{once:true});document.addEventListener("keydown",gesture,{once:true});audio.onplay=render;audio.onpause=render;render()}

addStyle();const wrap=document.createElement("div");wrap.className="ambient-controls";wrap.innerHTML='<button class="ambient-btn" id="ambientTheme" aria-label="Change theme">🎨</button><button class="ambient-btn" id="ambientMusic" aria-label="Toggle music">🔊</button>';document.body.appendChild(wrap);setupTheme(document.getElementById("ambientTheme"));setupMusic(document.getElementById("ambientMusic"));