const HUMANITY_API='https://api.worldbank.org/v2';
const HUMANITY_YEAR=365.25*86400;
const humanitySleep=ms=>new Promise(r=>setTimeout(r,ms));
const humanityFmt=n=>new Intl.NumberFormat('en-US').format(Math.max(0,Math.floor(Number.isFinite(n)?n:0)));
async function humanityJSON(url,retries=3){let last;for(let i=0;i<=retries;i++){try{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const j=await r.json();if(!Array.isArray(j)||!Array.isArray(j[1]))throw new Error('Invalid World Bank response');return j}catch(e){last=e;if(i<retries)await humanitySleep(700*(i+1));}}throw last;}
function humanityLatest(j){for(const x of j[1]||[]){const v=Number(x.value);if(Number.isFinite(v))return {value:v,year:Number(String(x.date).slice(0,4))};}return null;}
function humanityLatestByCode(j){const out=new Map();for(const x of j[1]||[]){const v=Number(x.value),y=Number(String(x.date).slice(0,4)),code=String(x.countryiso3code||'').toUpperCase();if(!/^[A-Z]{3}$/.test(code)||!Number.isFinite(v)||!Number.isFinite(y))continue;const old=out.get(code);if(!old||y>old.year)out.set(code,{value:v,year:y});}return out;}
async function humanityIndicator(indicator){const j=await humanityJSON(`${HUMANITY_API}/country/all/indicator/${indicator}?format=json&mrv=10&per_page=20000`);return {json:j,latest:humanityLatestByCode(j)};}
function humanityFlag(cc){return cc&&cc.length===2?cc.toUpperCase().replace(/./g,c=>String.fromCodePoint(127397+c.charCodeAt(0))):'🌐';}
function humanityProject(c,now=Date.now()){const base=Number(c.population);if(!Number.isFinite(base)||base<=0)return 0;const anchor=Date.UTC(Number(c.populationYear)||2024,6,1);const years=Math.max(0,(now-anchor)/1000/HUMANITY_YEAR);const net=(Number.isFinite(c.birthRate)&&Number.isFinite(c.deathRate))?(c.birthRate-c.deathRate)/1000:0;return base*Math.exp(net*years);}
const HUMANITY_AGGREGATES=new Set(['WLD','ARB','CSS','CEB','EAR','EAS','ECS','ECA','EMU','EAP','TEA','EUU','FCS','HPC','HIC','IBD','IBT','IDA','IDB','IDX','LAC','LCN','LDC','LIC','LMC','MEA','MNA','MIC','NAC','OED','OSS','PSS','PST','PRE','SAS','SSA','SSF','SST','UMC']);
function humanityUniverseFromPopulation(j){const seen=new Set(),out=[];for(const x of j?.[1]||[]){const iso=String(x?.countryiso3code||'').toUpperCase(),c=x?.country||{},iso2=String(c.iso2Code||c.id||'').toUpperCase(),name=String(c.value||'').trim();if(!/^[A-Z]{3}$/.test(iso)||HUMANITY_AGGREGATES.has(iso)||!/^[A-Z]{2}$/.test(iso2)||!name||seen.has(iso))continue;seen.add(iso);out.push({id:iso,iso2Code:iso2,name});}return out;}
async function humanityLoadData(){const popResult=await humanityIndicator('SP.POP.TOTL');const universe=humanityUniverseFromPopulation(popResult.json);if(universe.length<150)throw new Error(`Population indicator returned only ${universe.length} real countries`);const [birthResult,deathResult,worldPop,worldBirth,worldDeath]=await Promise.all([humanityIndicator('SP.DYN.CBRT.IN'),humanityIndicator('SP.DYN.CDRT.IN'),humanityJSON(`${HUMANITY_API}/country/WLD/indicator/SP.POP.TOTL?format=json&mrv=10&per_page=20`),humanityJSON(`${HUMANITY_API}/country/WLD/indicator/SP.DYN.CBRT.IN?format=json&mrv=10&per_page=20`),humanityJSON(`${HUMANITY_API}/country/WLD/indicator/SP.DYN.CDRT.IN?format=json&mrv=10&per_page=20`)]);const wp=humanityLatest(worldPop),wb=humanityLatest(worldBirth),wd=humanityLatest(worldDeath);if(!wp||!wb||!wd)throw new Error('Global demographic data unavailable');const countries=[];for(const c of universe){const p=popResult.latest.get(c.id);if(!p||p.value<=0)continue;const b=birthResult.latest.get(c.id),d=deathResult.latest.get(c.id);countries.push({iso:c.id,cc:c.iso2Code,name:c.name,population:p.value,populationYear:p.year,birthRate:b?.value,deathRate:d?.value,birthYear:b?.year,deathYear:d?.year,flag:humanityFlag(c.iso2Code)});}if(countries.length<150)throw new Error(`Only ${countries.length} real countries loaded`);const now=Date.now();countries.forEach(c=>{c.livePopulation=humanityProject(c,now);c.netPerSec=(Number.isFinite(c.birthRate)&&Number.isFinite(c.deathRate))?c.livePopulation*(c.birthRate-c.deathRate)/1000/HUMANITY_YEAR:0;});countries.sort((a,b)=>b.livePopulation-a.livePopulation);return {countries,world:{population:wp.value,year:wp.year,birthRate:wb.value,deathRate:wd.value,anchor:Date.UTC(wp.year,6,1)}};}
window.HumanityData={load:humanityLoadData,project:humanityProject,fmt:humanityFmt,YEAR:HUMANITY_YEAR};